aws:
- plugins/aws/**/*

custom:
- plugins/custom/**/*

commons:
- plugins/commons/**/*

manager:
- plugins/manager/**/*

logger:
- plugins/logger/**/*

helpers:
- internal/helpers/**/*

cli:
- internal/cli/**/*

report:
- internal/report/**/*

testdata:
- internal/testdata/**/*

breaking-changes:
- plugins/commons/types.go

dependencies:
- go.mod
- go.sum

main:
- main.go

makefile:
- Makefile

readme:
- README.md

github-actions:
- .github/workflows/*